import solutions from '../src/data/solutions.json'
import modules from '../src/data/modules.json'

type Env = { OPENAI_API_KEY: string }
type Action = 'analyse-work' | 'design-workflow' | 'design-agent' | 'check-governance' | 'implementation-plan' | 'build-learning-plan' | 'value-model' | 'executive-brief'
const validActions: Action[] = ['analyse-work', 'design-workflow', 'design-agent', 'check-governance', 'implementation-plan', 'build-learning-plan', 'value-model', 'executive-brief']
const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' }
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } })
function instruction(action: Action) { const names: Record<Action, string> = { 'analyse-work': 'Analyse a real task and return: What I understood; Current workflow; Where AI can help; What should stay human; Proposed human + AI workflow; Risks / questions; What is required to implement it; How to measure whether it worked.', 'design-workflow': 'Return: Inputs; steps; AI actions; human review; decision points; failure handling; outputs; implementation requirements.', 'design-agent': 'Return: agent purpose; instructions; required tools; permissions; prohibited actions; human handoff; test plan; success criteria.', 'check-governance': 'Return risk questions, possible controls, approvals to consider, human oversight and implementation conditions. Never call this formal approval.', 'implementation-plan': 'Return a practical phased implementation plan with discovery, controls, rollout, ownership and measurement.', 'build-learning-plan': 'Return a practical role-based learning plan tied to real work and supervised practice.', 'value-model': 'Return only a baseline, metric, collection method, measurement period and success criteria. Never invent ROI or achieved results.', 'executive-brief': 'Return a concise decision-focused brief: problem, proposed approach, safeguards, implementation requirements and measurement.' }; return names[action] }
// JSON module values are reviewed object records; TypeScript infers them too narrowly for the prompt payload spread.
// @ts-expect-error JSON module record spread
export default { async fetch(request: Request, env: Env): Promise<Response> { if (request.method === 'OPTIONS') return new Response(null, { headers: cors }); const url = new URL(request.url); const action = url.pathname.replace('/api/', '') as Action; if (request.method !== 'POST' || !validActions.includes(action)) return json({ error: 'Not found.' }, 404); if (!env.OPENAI_API_KEY) return json({ error: 'AI service is not configured.' }, 503); let payload: { solution_slug?: string; input?: Record<string, string> }; try { payload = await request.json() } catch { return json({ error: 'Invalid request body.' }, 400) } const solution = (solutions as { slug: string; company: string; role: string; brief_summary: string; agent_summary: string; module_ids: string[]; human_judgement: string }[]).find(x => x.slug === payload.solution_slug); const input = Object.values(payload.input || {}).filter(Boolean).join('\n'); if (!solution) return json({ error: 'Unknown reviewed solution.' }, 404); if (!input.trim()) return json({ error: 'Provide real work or context to analyse.' }, 400); const selectedModules = solution.module_ids.map(id => ({ id, ...(modules as Record<string, unknown>)[id] })); const prompt = `You are the OUTLINED solution architect. The reviewed public job brief is the sole factual source for this company.\nCompany: ${solution.company}\nRole: ${solution.role}\nReviewed public brief: ${solution.brief_summary}\nOur proposed custom system: ${solution.agent_summary}\nRelevant reusable capabilities: ${JSON.stringify(selectedModules)}\nHuman judgement to preserve: ${solution.human_judgement}\n\nVisitor's real input:\n${input}\n\nTask: ${instruction(action)}\n\nRules: Do real analysis, grounded in the specific solution. Do not state or imply this company uses, approved, has deployed, or endorses OUTLINED. Do not invent company policies, integrations, data, adoption figures, savings, ROI or facts. Clearly flag assumptions and keep accountable human judgement visible. For regulated contexts, frame controls as matters to consider, not formal approval. Use concise useful headings and plain language.`; try { const upstream = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'gpt-5-mini', input: prompt }) }); if (!upstream.ok) return json({ error: 'The upstream AI service could not complete the request.' }, 502); const data = await upstream.json() as { output_text?: string }; if (!data.output_text) return json({ error: 'The upstream AI service returned no analysis.' }, 502); return json({ output: data.output_text }) } catch { return json({ error: 'The upstream AI service is unavailable.' }, 502) } } }
