import { useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import jobs from './data/jobs.json'
import solutions from './data/solutions.json'
import modules from './data/modules.json'
import type { ActionName, Job, Module, Solution } from './types'

const publicJobs = (jobs as Job[]).filter((job) => job.public_page === 'Yes')
const solutionList = solutions as Solution[]
const moduleMap = modules as Record<string, Module>
const actions: { key: ActionName; label: string; fields: { key: string; label: string; placeholder: string }[] }[] = [
  { key: 'analyse-work', label: 'Analyse a real piece of work', fields: [{ key: 'task', label: 'Describe the task or process', placeholder: 'Every Monday I collect information from five spreadsheets, compare it with last week and prepare a management report.' }] },
  { key: 'design-workflow', label: 'Design a workflow', fields: [{ key: 'task', label: 'Task', placeholder: 'Describe the work to redesign' }, { key: 'frequency', label: 'Frequency', placeholder: 'e.g. weekly' }, { key: 'tools', label: 'Current tools', placeholder: 'e.g. Excel, email' }, { key: 'result', label: 'Desired result', placeholder: 'What should the workflow produce?' }] },
  { key: 'design-agent', label: 'Design an agent', fields: [{ key: 'responsibility', label: 'Repeatable responsibility', placeholder: 'What would the agent be responsible for?' }, { key: 'inputs', label: 'Inputs', placeholder: 'What information may it use?' }, { key: 'boundaries', label: 'Boundaries', placeholder: 'What must it never do?' }] },
  { key: 'check-governance', label: 'Run a governance pre-check', fields: [{ key: 'useCase', label: 'AI use case', placeholder: 'Describe the proposed use' }, { key: 'data', label: 'Data involved', placeholder: 'What data may be involved?' }, { key: 'audience', label: 'Audience', placeholder: 'Who will use or receive it?' }, { key: 'decisions', label: 'Decisions affected', placeholder: 'Which decisions could be affected?' }] },
  { key: 'implementation-plan', label: 'Create an implementation plan', fields: [{ key: 'context', label: 'Team and work context', placeholder: 'Describe the team, problem and desired change.' }] },
  { key: 'build-learning-plan', label: 'Build a role learning plan', fields: [{ key: 'context', label: 'Role and real work', placeholder: 'Describe the role and the tasks people need to learn.' }] },
  { key: 'value-model', label: 'Build a value framework', fields: [{ key: 'baseline', label: 'Current baseline', placeholder: 'Describe the current time, quality, cost or effort.' }] },
  { key: 'executive-brief', label: 'Create an executive brief', fields: [{ key: 'context', label: 'Initiative context', placeholder: 'Describe the initiative, audience and decision required.' }] }
]
function fmt(date: string) { return new Intl.DateTimeFormat('en-AU', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`)) }
export function Home() { return <><section className="hero"><p className="eyebrow">Public AI role briefs, made tangible</p><h1>AI roles companies are hiring for.<br /><em>Solutions our agent has outlined around them.</em></h1><p className="lede">Companies are creating new roles to work out how AI should operate inside their organisations. We study each public brief, identify the work it points to and design a custom system around it.</p><Link className="button" to="/jobs">Explore the job map <span>→</span></Link></section><section className="statement"><p className="eyebrow">The premise</p><h2>A public job advertisement can be a remarkably clear brief.</h2><p>OUTLINED is independent research and a working demonstration of AI adoption, workflow design and safe human oversight—not software sold to the organisations listed.</p></section></> }
export function Jobs() { const [query, setQuery] = useState(''); const [sector, setSector] = useState(''); const [role, setRole] = useState(''); const sectors = [...new Set(publicJobs.map(j => j.sector))].sort(); const roles = [...new Set(publicJobs.map(j => j.role))].sort(); const filtered = useMemo(() => publicJobs.filter(j => `${j.company} ${j.role} ${j.need}`.toLowerCase().includes(query.toLowerCase()) && (!sector || j.sector === sector) && (!role || j.role === role)), [query, sector, role]); return <section className="page"><p className="eyebrow">The job map</p><h1>Roles that reveal the work ahead.</h1><p className="lede">Named organisations only. Every page is based on a reviewed public source.</p><div className="filters"><input aria-label="Search jobs" placeholder="Search company, role or need" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Filter by sector" value={sector} onChange={e => setSector(e.target.value)}><option value="">All sectors</option>{sectors.map(x => <option key={x}>{x}</option>)}</select><select aria-label="Filter by role" value={role} onChange={e => setRole(e.target.value)}><option value="">All role types</option>{roles.map(x => <option key={x}>{x}</option>)}</select></div><p className="count">{filtered.length} reviewed roles</p><div className="grid">{filtered.map(j => <article className="job-card" key={j.page_slug}><p className="sector">{j.sector}</p><h2>{j.company}</h2><h3>{j.role}</h3><p>{j.need}</p><div className="meta">Verified {fmt(j.verified_on)}</div><Link to={`/solutions/${j.page_slug}`}>View solution <span>→</span></Link></article>)}</div></section> }
function ActionPanel({ solution }: { solution: Solution }) { const [selected, setSelected] = useState<ActionName>('analyse-work'); const [values, setValues] = useState<Record<string, string>>({}); const [response, setResponse] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const action = actions.find(x => x.key === selected)!; async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); setResponse(''); if (!action.fields.some(field => values[field.key]?.trim())) { setError('Enter real work or context before continuing.'); return } setLoading(true); try { const base = import.meta.env.VITE_API_BASE_URL || ''; const res = await fetch(`${base}/api/${selected}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ solution_slug: solution.slug, input: values }) }); const body = await res.json() as { output?: string; error?: string }; if (!res.ok || !body.output) throw new Error(body.error || 'The analysis service could not complete the request.'); setResponse(body.output) } catch (err) { setError(err instanceof Error ? err.message : 'The analysis service could not complete the request.') } finally { setLoading(false) } } return <section className="action" id="try-it"><p className="eyebrow">Try it on real work</p><h2>{action.label}</h2><p>This sends your input to the live AI service. It is not stored by OUTLINED by default.</p><div className="action-tabs">{actions.map(item => <button className={item.key === selected ? 'active' : ''} onClick={() => { setSelected(item.key); setResponse(''); setError('') }} key={item.key} type="button">{item.label}</button>)}</div><form onSubmit={submit}>{action.fields.map(field => <label key={field.key}>{field.label}<textarea required={action.fields.length === 1} value={values[field.key] || ''} placeholder={field.placeholder} onChange={e => setValues({ ...values, [field.key]: e.target.value })} /></label>)}<button className="button" disabled={loading}>{loading ? 'Analysing…' : 'Run real analysis →'}</button></form>{error && <p role="alert" className="error">{error}</p>}{response && <article className="response"><p className="eyebrow">Live AI response</p><div>{response.split('\n').map((line, i) => line.trim() ? <p key={i}>{line}</p> : null)}</div></article>}</section> }
export function SolutionPage() { const { slug } = useParams(); const solution = solutionList.find(x => x.slug === slug); if (!solution) return <section className="page not-found"><h1>Solution not found.</h1><p>This route does not match a reviewed public solution.</p><Link className="button" to="/jobs">Return to the job map</Link></section>; return <><section className="solution-hero"><p className="eyebrow">Public role brief · verified {fmt(solution.verified_on)}</p><h1>{solution.company}</h1><h2>{solution.role}</h2></section><section className="solution-section"><p className="eyebrow">What the role is trying to achieve</p><p className="big-copy">{solution.brief_summary}</p></section><section className="reveal"><p className="eyebrow">{solution.agent_heading}</p><h2>{solution.solution_name}</h2><p>{solution.agent_summary}</p></section><section className="solution-section"><p className="eyebrow">The custom system</p><div className="modules">{solution.module_ids.map(id => <article key={id}><span>{String(solution.module_ids.indexOf(id) + 1).padStart(2, '0')}</span><h3>{moduleMap[id]?.name || id}</h3><p>{moduleMap[id]?.description}</p></article>)}</div></section><ActionPanel solution={solution} /><section className="human"><p className="eyebrow">What remains human</p><p>{solution.human_judgement}</p></section><section className="source"><p className="eyebrow">Public job source</p><a href={solution.source_url} target="_blank" rel="noreferrer">Open original public job advertisement ↗</a><p>Verified {fmt(solution.verified_on)}</p><small>{solution.disclaimer}</small></section></> }
export function About() { return <section className="page prose"><p className="eyebrow">About OUTLINED</p><h1>Proof of work, before the interview.</h1><p>OUTLINED treats public AI adoption, enablement and governance job advertisements as research briefs. Each solution is independently designed around the stated role—without claiming affiliation, deployment or endorsement.</p><p>The underlying components are reusable, but the architecture, language, safeguards and real AI interactions are grounded in the individual reviewed brief. Visitor input is sent only to the configured AI provider to generate the requested response and is not stored by this application.</p><Link className="button" to="/jobs">See the job map</Link></section> }
